#!/bin/bash -e

echo "[.vim/run] cmake $BUILD_TYPE"
cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B build .

echo "[.vim/run] make"
cd build && make

echo "[.vim/run] tests"
./tests

echo "[.vim/run] performance benchmarks"
for benchmark in benchmark_*; do
  ./$benchmark # --benchmark_format=json
done
